# Generated by Django 5.1.3 on 2024-11-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_address_userprofile_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
