# Generated by Django 5.1.3 on 2024-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userprofile_alias_remove_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
