# Generated by Django 5.1.3 on 2024-11-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
